/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"


void
programa_compartir_canciones_2(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * crear_archivo_2_2_arg;
	int  *result_2;
	bloque2  enviar_bloque_2_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, programa_compartir_canciones, programa_compartir_canciones_version_2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = crear_archivo_2_2(&crear_archivo_2_2_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = enviar_bloque_2_2(&enviar_bloque_2_2_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programa_compartir_canciones_2 (host);
exit (0);
}
