/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface1.h"

bool_t
xdr_cancion1 (XDR *xdrs, cancion1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoCancion))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->artista, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tamanioCancion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bloque1 (XDR *xdrs, bloque1 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreArchivo, TAM_MAX_NOM_ARCHIVO))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datos.datos_val, (u_int *) &objp->datos.datos_len, TAM_MAX_BLOQUE_ARCHIVO))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dest_offset))
		 return FALSE;
	return TRUE;
}
