/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface3.h"

bool_t
xdr_datos_calculados (XDR *xdrs, datos_calculados *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_hora, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidad_canciones_mp3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidad_canciones_FLAC))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->espacio_total_canciones))
		 return FALSE;
	return TRUE;
}
