/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <stdbool.h>
#include "interface1.h"
#include "interface2.h"
#include "interface3.h"
cancion1 vectorCanciones[20];
int indice = 0;
struct stat st; 
const char *name = "canciones";
int tamanio_cancion = 0; 
int tamanio_bloques = 0;
int tamanio_mb_canciones = 0;

/**
 * @brief Método para partir una línea 
 * 
 * @param couple 
 * @param tosplit 
 * @param culprit 
 * @return char** retorno. 
 */
char** split( char** couple, char* tosplit, char* culprit ) { 
    int i = 0; 
    // Returns first token  
    char *token = strtok( tosplit, culprit);    
    for( int i = 0; token != NULL && i < 2; i++ ) { 
        couple[i] = token; 
        token = strtok(NULL, culprit); 
    } 
    return couple;
}
/**
 * @brief Obtener la extensión de un archivo 
 * 
 * @param filename nombre del archivo 
 * @return const char* retorno. 
 */
const char * get_filename_ext(const char *filename) {
	const char *dot = strrchr(filename, '.');
	if(!dot || dot == filename) return "";
	return dot + 1;
}
/**
 * @brief Método para enviar la canción al servidor
 * 
 * @param nombreArchivo nombre del archivo a enviar
 * @param clnt referencia del cliente que enviará el archivo al servidor. 
 */
void enviarArchivoAlServidor(char * nombreArchivo, CLIENT  *clnt){

	//fopen abrimos el archivo en modo lectura r 
	FILE *file = fopen(nombreArchivo, "r");
	bool bandera = TRUE; 
	int pos = 0, cantidadBloques = 0; 
	bloque1 objBloque; 
	// objBloque.nombreArchivo = (char*)malloc(40*sizeof(char));
	objBloque.nombreArchivo = (char*)malloc(200);
	strcpy(objBloque.nombreArchivo, nombreArchivo);
	objBloque.datos.datos_val = (char *)malloc(TAM_MAX_BLOQUE_ARCHIVO * sizeof(char));

	do{
	//la funcion fread lee 1024 bytes del archivo 
	//los guarda en el campo datos_val del campo datos, de la variable objBLoque
		objBloque.datos.datos_len = fread(objBloque.datos.datos_val, 1, TAM_MAX_BLOQUE_ARCHIVO, file);
		//el campo dest_offset almacena la posición desde la cual se realizar la lectura de los 1024 bytes
		objBloque.dest_offset = pos; 
		pos = pos + objBloque.datos.datos_len; 

		int *resultado = enviar_bloque_2_2(&objBloque, clnt);
		if(resultado == (int *) NULL){
			clnt_perror(clnt, "call failed");
			bandera = FALSE; 
		}else{
			cantidadBloques ++; 
		}
		//si el ultimo bloque es menor a 1024, es el ultimo bloque del archivo
	} while (objBloque.datos.datos_len == TAM_MAX_BLOQUE_ARCHIVO);

	free(objBloque.datos.datos_val);
	fclose(file);

	if(bandera == TRUE){
		printf("\n Canción enviar exitosamente a partir de %d bloques", cantidadBloques);
	}else{
		printf("\n Error al enviar la canción");
	}
}
/**
 * @brief Método para enviar la notificacion al servidor de logs. 
 * 
 */
void enviarNotificacion(){
	printf("\n llego a enviar notificacion: ");
	int num_canciones_mp3 = 0; 
	int num_canciones_FLAC = 0;
	int tamanio_arreglo = sizeof(vectorCanciones);
	// Memoria ocupada por su primer elemento
	int tamanio_pos = sizeof(vectorCanciones[0]);

	// División simple
	int longitud = tamanio_arreglo / tamanio_pos;
	printf("\n %d", tamanio_arreglo);
	printf("\n %d", tamanio_pos);
	printf("\n %d", longitud);
	//TODO hacer calcular 
	//1. calcular la cantidad de canciones segun el tipo 
	for (size_t i = 0; i < 5; i++){
		//vertificar el tipo de cancion 
		if(vectorCanciones[i].titulo != '\0'){
			printf("\n entra en el if %s", vectorCanciones[i].tipo);
			if(strcmp(vectorCanciones[i].tipo, "mp3") == 0){
				num_canciones_mp3++;
			}else if(strcmp(vectorCanciones[i].tipo, "FLAC") == 0){
				num_canciones_FLAC++;
			}	
		}

	}
	printf("\n numero cancion: %d ", num_canciones_mp3);


}

/**
 * @brief Recibe los datos de la canción y los guarda en un vector de canciones 
 * 
 * @param argp struct con los datos de la canción 
 * @param rqstp 
 * @return bool_t* resturna true o false si es correcto o incorrecto según corresponda
 */
bool_t * enviar_datos_cancion_1_1_svc(cancion1 *argp, struct svc_req *rqstp) {
	static bool_t  result;

	printf("\nInvocando a registrar canción");
	printf("\nDatos de la canción a registrar");
	printf("\nId de la canción %d", argp->codigoCancion);
	printf("\nTítulo de la canción %s", argp->titulo);
	printf("\nArtista de la canción %s", argp->artista);
	printf("\n");
	
	//guardo la canción 
	if(indice != 6){
	vectorCanciones[indice] = *argp;
	result = TRUE;
	}else{
		result = FALSE;
	}
	indice++;
	printf("\n el resultado fue : %B", result);
	return &result;
}
/**
 * @brief Recibe la canción y la guarda en la carpeta (Canciones)
 * 
 * @param argp nombre del archivo 
 * @param rqstp 
 * @return int* Retorna 1 si es correcto y 0 si hay fallo 
 */
int * crear_archivo_1_1_svc(char **argp, struct svc_req *rqstp){
	static int  result;

	printf("\n Invocando a crear canciones");
	printf("\n");

	//creo la carpeta la primera vez 
	if (stat(name, &st) == -1){
        mkdir(name, S_IRWXU); //lo creo con permisos 
        printf("Directorio canciones creado con exito\n");
    }

	int len = strlen("canciones/");
    char *ruta = malloc(len + strlen(*argp) + 1);
    sprintf(ruta, "canciones/%s", *argp);

	fopen(ruta, "w");
	//fopen crea el archivo si no existe y w para escritura
	return &result;

}
/**
 * @brief Recibe todos los bloques de la cancion y los guarda en canciones/name_cancion.extension
 * 
 * @param argp bloque de cancion 
 * @param rqstp 
 * @return int* Retorna 1 si es correcto, 0 si es incorrecto. 
 */
int * enviar_bloque_1_1_svc(bloque1 *argp, struct svc_req *rqstp) {

	static int  result;
	result = 0; 
	FILE *file;
	//abrimos el archivo en modo añadir a -> agrega contenido al final  
	int len = strlen("canciones/");
    char *ruta = malloc(len + strlen(argp) + 1);
    sprintf(ruta, "canciones/%s", (*argp).nombreArchivo);

	file = fopen(ruta, "a");
	if(file == NULL){
		result = 1;
	}

	fseek(file, (*argp).dest_offset, SEEK_SET);
	fwrite((*argp).datos.datos_val, 1, (*argp).datos.datos_len, file);
	fclose(file);
	//toca ir acumulando los bytes
	tamanio_cancion = tamanio_cancion + (*argp).datos.datos_len;
	tamanio_bloques++;

	if((*argp).dest_offset == 0){
		printf("\n Primer bloque recibido exitosamente");
		printf("\n");
	}
	else if((*argp).datos.datos_len < TAM_MAX_BLOQUE_ARCHIVO){
		printf("\n Último bloque recibido exitosamente");
		printf("\n Número de bloques recibidos: %d", tamanio_bloques);
		
		//sumar el tamanio a la variable global 
		tamanio_mb_canciones = tamanio_mb_canciones + tamanio_cancion;
		//renombramiento de la cancion 
		int n1 = tamanio_cancion; 
		char *num;
		char buffer[100];
		int len2 = strlen("canciones/");
    	char *ruta2 = malloc(len2 + strlen(argp) + 1);
		char *nombreCancion = malloc(len2 + strlen(argp) + 1); 

		//convertimos un int a char 
		if (asprintf(&num, "_%d", n1) == -1) {
			perror("No se pudo hacer la coherción de tipo");
		} else {
			//ruta inicial de la cancion 
    		sprintf(ruta2, "canciones/%s", (*argp).nombreArchivo);
			//split para el nombre de la cancion 
			char delimitador[] = ".";
			char *token = strtok(ruta, delimitador);
			//concatenacion para el nombre nuevo de la cancion 
			strcat(token, num);
			strcat(token, ".mp3");
			rename(ruta2, token);
			free(num);
			//formateo el nombre de la cancion para enviar al servidor de respaldo
			char delimitador_formato[] = "/";
			char *nombreFormateado = strtok(token, delimitador_formato);
			if(nombreFormateado != NULL){
				// Sólo en la primera pasamos la cadena; en las siguientes pasamos NULL
				nombreFormateado = strtok(NULL, delimitador_formato);
				printf("Token: %s\n", nombreFormateado);
    		}
			printf("\n impresion nueva: %s", nombreFormateado);
			nombreCancion = nombreFormateado;
			printf("\n impresion: %s", token);
			printf("\n impresion 2: %s", ruta2);
		}

		//Si el archivo se recibió exitosamente hacemos una copia de seguridad en el servidor 
		//de respaldo 
		
		CLIENT *clnt;
		int  *result_1;
		char * crear_archivo_2_2_arg;
		int  *result_2;
		bloque2  enviar_bloque_2_2_arg;
		//reservo memoria 
		crear_archivo_2_2_arg = (char*)malloc(40*sizeof(char));
		// crear_archivo_2_2_arg = (*argp).nombreArchivo;
		printf("\n ruta2 : %s", nombreCancion);
		crear_archivo_2_2_arg = nombreCancion;
		
		#ifndef	DEBUG
			clnt = clnt_create ("localhost", programa_compartir_canciones2, programa_compartir_canciones_version_2, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror ("localhost");
				exit (1);
			}
		#endif	/* DEBUG */
			printf("\n llega hasta antes de crear_archivo_2");
			result_1 = crear_archivo_2_2(&crear_archivo_2_2_arg, clnt);
			printf("\n llega hasta despues de crear_archivo_2 %d", result_1);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				//TODO enviar la cancion al servidor de respaldo 
				printf("\n Archivo vacío creado en el servidor");
				printf("\n Procedimiento a enviar en bloques el archivo");
				printf("%s ", crear_archivo_2_2_arg);
				enviarArchivoAlServidor(crear_archivo_2_2_arg, clnt);

				//TODO enviar notificacion al servidor de logs
				printf("\n antes de enviar notificacion");
				enviarNotificacion();
			}

			// result_2 = enviar_bloque_2_2(&enviar_bloque_2_2_arg, clnt);
			// if (result_2 == (int *) NULL) {
			// 	clnt_perror (clnt, "call failed");
			// }else{
			// 	printf("\n No se pudo enviar el archivo al servidor de respaldo");	
			// }
		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */

	}
	return &result;
}
/**
 * @brief Funcion que simula el comportamiento de un cliente para comunicarse con el 
 * serividor de respaldo. 
 * 
 * @return int* 1 si es correcto y 0 en caso contrario 
 */
int crear_archivo_servidor_respaldo(){
	printf("/holi ");
	static int  result_response;

	static char * result;
	CLIENT *clnt;
	int  *result_1;
	int  notificacion;

	printf("\n Enviando cancion al servidor de respaldo");

	#ifndef	DEBUG
	clnt = clnt_create ("localhost", programa_compartir_canciones, programa_compartir_canciones_version_2, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror ("localhost");
		exit (1);
	}
	#endif	/* DEBUG */
	
	//Enviamos la cancion al servidor de respaldo
	result_1 = crear_archivo_2_2("nombre prueba", clnt);
	/*if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else if(*result_1 == TRUE){
		printf("\n Archivo vacío creado en el servidor");
		printf("\n Procedimiento a enviar en bloques el archivo");
		enviarArchivoAlServidor(crear_archivo_1_1_arg, clnt);
	}else{
		printf("\n Error al registrar la cancion");
	}*/
	
	
	// #ifndef	DEBUG
		// clnt_destroy (clnt);
	// #endif	 /* DEBUG */

	// return (void *) &result;
	// static int  result;

	result_response = 1;


	return result_response; 
}

cancion1 * consultar_cancion_1_1_svc(char **argp, struct svc_req *rqstp) {
	static cancion1  result;

	/*
	 * insert server code here
	 */

	return &result;
}
