/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface3.h"
/**
 * @brief metodo del lado del servidor para recibir la notificación e imprimirla por pantalla. 
 * 
 * @param argp estructura con los datos calculados
 * @param rqstp servicio request 
 * @return void* 
 */
void * enviar_notificacion_3_svc(datos_calculados *argp, struct svc_req *rqstp){
	static char * result;

	printf("\nNotificacion");
	printf("\nFecha y hora del registro de la cancion: %s", argp->fecha_hora);
	printf("\nCantidad de canciones tipo .mp3 registradas%d", argp->cantidad_canciones_mp3);
	printf("\nCantidad de canciones tipo .FLAC registradas %d", argp->cantidad_canciones_FLAC);
	printf("\nEspacio utilizado por todas las canciones en mb %d", argp->espacio_total_canciones);
	printf("\n");
	result = 1;

	return (void *) &result;
}
